-- --- 1. TABLES ---
CREATE TABLE IF NOT EXISTS VITALIS_DEV.APP.CUSTOMER_SOURCE (SOURCE_ID VARCHAR PRIMARY KEY, SOURCE_NAME VARCHAR, IS_ACTIVE BOOLEAN DEFAULT TRUE);

CREATE TABLE IF NOT EXISTS VITALIS_DEV.APP.CUSTOMER (
    CUSTOMER_ID VARCHAR PRIMARY KEY, CUSTOMER_NAME VARCHAR, EMAIL VARCHAR, PHONE VARCHAR,
    SOURCE_ID VARCHAR, DATE_OF_BIRTH DATE, GENDER VARCHAR, NOTES VARCHAR,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(), UPDATED_AT TIMESTAMP, IS_DELETED BOOLEAN DEFAULT FALSE, DELETED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS VITALIS_DEV.APP.CUSTOMER_REPORT (
    REPORT_ID VARCHAR PRIMARY KEY, CUSTOMER_ID VARCHAR, ORIGINAL_FILENAME VARCHAR, STAGE_PATH VARCHAR,
    EXTRACTION_DATA VARIANT, IS_EXTRACTED BOOLEAN DEFAULT FALSE, EXTRACTED_AT TIMESTAMP,
    UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(), IS_DELETED BOOLEAN DEFAULT FALSE, DELETED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS VITALIS_DEV.APP.REPORT_MARKER (
    MARKER_ID VARCHAR PRIMARY KEY, REPORT_ID VARCHAR, CUSTOMER_ID VARCHAR, LAB_NAME VARCHAR,
    PATIENT_NAME VARCHAR, REPORT_SECTION VARCHAR, MARKER_NAME VARCHAR, RESULT VARCHAR, UNIT VARCHAR,
    REFERENCE_VALUES VARCHAR, WITHIN_RANGE VARCHAR, IS_DELETED BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS VITALIS_DEV.APP.ACTIVITY_LOG (
    LOG_ID VARCHAR PRIMARY KEY, CUSTOMER_ID VARCHAR, ACTION VARCHAR, DETAILS VARCHAR, USER_NAME VARCHAR,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- --- 2. STORED PROCEDURES (YOUR API) ---

-- SP: Add Customer
CREATE OR REPLACE PROCEDURE VITALIS_DEV.APP.SP_ADD_CUSTOMER(
    p_id VARCHAR, p_name VARCHAR, p_email VARCHAR, p_phone VARCHAR,
    p_source_id VARCHAR, p_dob VARCHAR, p_gender VARCHAR, p_notes VARCHAR, p_user VARCHAR
)
RETURNS VARCHAR LANGUAGE SQL AS $$
BEGIN
    INSERT INTO VITALIS_DEV.APP.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, EMAIL, PHONE, SOURCE_ID, DATE_OF_BIRTH, GENDER, NOTES, UPDATED_AT)
    SELECT :p_id, :p_name, :p_email, :p_phone, :p_source_id, TRY_TO_DATE(:p_dob), :p_gender, :p_notes, CURRENT_TIMESTAMP();

    INSERT INTO VITALIS_DEV.APP.ACTIVITY_LOG (LOG_ID, CUSTOMER_ID, ACTION, DETAILS, USER_NAME)
    SELECT UUID_STRING(), :p_id, 'CREATED', 'Customer added', :p_user;

    RETURN 'SUCCESS';
END;
$$;

-- SP: Update Customer Info
CREATE OR REPLACE PROCEDURE VITALIS_DEV.APP.SP_UPDATE_CUSTOMER(
    p_id VARCHAR, p_name VARCHAR, p_email VARCHAR, p_phone VARCHAR,
    p_source_id VARCHAR, p_dob VARCHAR, p_gender VARCHAR, p_user VARCHAR
)
RETURNS VARCHAR LANGUAGE SQL AS $$
BEGIN
    UPDATE VITALIS_DEV.APP.CUSTOMER
    SET CUSTOMER_NAME = :p_name, EMAIL = :p_email, PHONE = :p_phone,
        SOURCE_ID = :p_source_id, DATE_OF_BIRTH = TRY_TO_DATE(:p_dob), GENDER = :p_gender, UPDATED_AT = CURRENT_TIMESTAMP()
    WHERE CUSTOMER_ID = :p_id;

    INSERT INTO VITALIS_DEV.APP.ACTIVITY_LOG (LOG_ID, CUSTOMER_ID, ACTION, DETAILS, USER_NAME)
    SELECT UUID_STRING(), :p_id, 'UPDATED', 'Customer info updated', :p_user;

    RETURN 'SUCCESS';
END;
$$;

-- SP: Update Notes
CREATE OR REPLACE PROCEDURE VITALIS_DEV.APP.SP_UPDATE_NOTES(p_id VARCHAR, p_notes VARCHAR, p_user VARCHAR)
RETURNS VARCHAR LANGUAGE SQL AS $$
BEGIN
    UPDATE VITALIS_DEV.APP.CUSTOMER SET NOTES = :p_notes, UPDATED_AT = CURRENT_TIMESTAMP() WHERE CUSTOMER_ID = :p_id;
    INSERT INTO VITALIS_DEV.APP.ACTIVITY_LOG (LOG_ID, CUSTOMER_ID, ACTION, DETAILS, USER_NAME) 
    SELECT UUID_STRING(), :p_id, 'NOTES_UPDATED', 'Notes updated', :p_user;
    RETURN 'SUCCESS';
END;
$$;

-- SP: Delete Customer
CREATE OR REPLACE PROCEDURE VITALIS_DEV.APP.SP_DELETE_CUSTOMER(p_id VARCHAR, p_user VARCHAR)
RETURNS VARCHAR LANGUAGE SQL AS $$
BEGIN
    UPDATE VITALIS_DEV.APP.CUSTOMER SET IS_DELETED = TRUE, DELETED_AT = CURRENT_TIMESTAMP() WHERE CUSTOMER_ID = :p_id;
    UPDATE VITALIS_DEV.APP.CUSTOMER_REPORT SET IS_DELETED = TRUE, DELETED_AT = CURRENT_TIMESTAMP() WHERE CUSTOMER_ID = :p_id;
    UPDATE VITALIS_DEV.APP.REPORT_MARKER SET IS_DELETED = TRUE WHERE CUSTOMER_ID = :p_id;

    INSERT INTO VITALIS_DEV.APP.ACTIVITY_LOG (LOG_ID, CUSTOMER_ID, ACTION, DETAILS, USER_NAME) 
    SELECT UUID_STRING(), :p_id, 'DELETED', 'Customer deleted', :p_user;
    RETURN 'SUCCESS';
END;
$$;

-- SP: Add Report
CREATE OR REPLACE PROCEDURE VITALIS_DEV.APP.SP_ADD_REPORT(p_report_id VARCHAR, p_customer_id VARCHAR, p_filename VARCHAR, p_stage_path VARCHAR, p_user VARCHAR)
RETURNS VARCHAR LANGUAGE SQL AS $$
BEGIN
    INSERT INTO VITALIS_DEV.APP.CUSTOMER_REPORT (REPORT_ID, CUSTOMER_ID, ORIGINAL_FILENAME, STAGE_PATH) 
    SELECT :p_report_id, :p_customer_id, :p_filename, :p_stage_path;
    
    INSERT INTO VITALIS_DEV.APP.ACTIVITY_LOG (LOG_ID, CUSTOMER_ID, ACTION, DETAILS, USER_NAME) 
    SELECT UUID_STRING(), :p_customer_id, 'REPORT_UPLOADED', :p_filename, :p_user;
    
    RETURN 'SUCCESS';
END;
$$;

-- SP: Delete Report
CREATE OR REPLACE PROCEDURE VITALIS_DEV.APP.SP_DELETE_REPORT(p_report_id VARCHAR, p_customer_id VARCHAR, p_user VARCHAR)
RETURNS VARCHAR LANGUAGE SQL AS $$
BEGIN
    UPDATE VITALIS_DEV.APP.CUSTOMER_REPORT SET IS_DELETED = TRUE, DELETED_AT = CURRENT_TIMESTAMP() WHERE REPORT_ID = :p_report_id;
    UPDATE VITALIS_DEV.APP.REPORT_MARKER SET IS_DELETED = TRUE WHERE REPORT_ID = :p_report_id;
    
    INSERT INTO VITALIS_DEV.APP.ACTIVITY_LOG (LOG_ID, CUSTOMER_ID, ACTION, DETAILS, USER_NAME) 
    SELECT UUID_STRING(), :p_customer_id, 'REPORT_DELETED', 'Report deleted', :p_user;
    
    RETURN 'SUCCESS';
END;
$$;

-- SP: Extract Report
CREATE OR REPLACE PROCEDURE VITALIS_DEV.APP.SP_EXTRACT_REPORT(
    p_report_id VARCHAR, p_customer_id VARCHAR, p_stage_path VARCHAR, p_user VARCHAR
)
RETURNS VARCHAR LANGUAGE SQL AS $$
DECLARE
    v_data VARIANT;
    v_parsed VARIANT;
    v_instr VARCHAR := 'Try to parse the result as a numeric value then understand the reference range. If the result falls within the reference range then write Yes. If the result falls out of the reference range write No. If the reference is null then put null. If you are not 100% sure keep it null.If the result means non-diabetic write Yes. Dont write your thinking steps just answer with with one word Yes, No, or Null';
BEGIN
    -- 1. Extract the JSON from Document AI
    SELECT VITALIS_DEV.APP.EXTRACT_LAB_REPORT(:p_stage_path) INTO :v_data;

    IF (:v_data IS NULL OR :v_data = '') THEN
        RETURN 'Extraction failed: No data returned.';
    END IF;

    -- Ensure we cast the returned string into true JSON variant
    v_parsed := PARSE_JSON(:v_data);

    -- 2. Update Report metadata
    UPDATE VITALIS_DEV.APP.CUSTOMER_REPORT
    SET EXTRACTION_DATA = :v_parsed, IS_EXTRACTED = TRUE, EXTRACTED_AT = CURRENT_TIMESTAMP()
    WHERE REPORT_ID = :p_report_id;

    -- Clear old markers
    DELETE FROM VITALIS_DEV.APP.REPORT_MARKER WHERE REPORT_ID = :p_report_id;

    -- 3. Insert markers AND run the AI_COMPLETE logic
    INSERT INTO VITALIS_DEV.APP.REPORT_MARKER (
        MARKER_ID, REPORT_ID, CUSTOMER_ID, LAB_NAME, PATIENT_NAME,
        REPORT_SECTION, MARKER_NAME, RESULT, UNIT, REFERENCE_VALUES, WITHIN_RANGE
    )
    SELECT
        MARKER_ID, REPORT_ID, CUSTOMER_ID, LAB_NAME, PATIENT_NAME, REPORT_SECTION, MARKER_NAME, RESULT, UNIT, REFERENCE_VALUES,
        CASE
            WHEN UPPER(ai_raw) LIKE '%YES%' THEN 'Yes'
            WHEN UPPER(ai_raw) LIKE '%NO%' THEN 'No'
            ELSE 'Null'
        END
    FROM (
        SELECT
            :p_report_id || '_' || m.index AS MARKER_ID,
            :p_report_id AS REPORT_ID,
            :p_customer_id AS CUSTOMER_ID,
            CAST(:v_parsed:response:lab_name AS STRING) AS LAB_NAME,
            CAST(:v_parsed:response:patient_name AS STRING) AS PATIENT_NAME,
            COALESCE(CAST(:v_parsed:response:lab_markers:report_section[m.index] AS STRING), CAST(:v_parsed:response:report_section AS STRING), 'Unknown') AS REPORT_SECTION,
            CAST(:v_parsed:response:lab_markers:marker_name[m.index] AS STRING) AS MARKER_NAME,
            CAST(:v_parsed:response:lab_markers:result[m.index] AS STRING) AS RESULT,
            CAST(:v_parsed:response:lab_markers:unit[m.index] AS STRING) AS UNIT,
            CAST(:v_parsed:response:lab_markers:reference_values[m.index] AS STRING) AS REFERENCE_VALUES,
            AI_COMPLETE('openai-gpt-5-mini', :v_instr || ' Result: ' || COALESCE(CAST(:v_parsed:response:lab_markers:result[m.index] AS STRING), 'N/A') || ' Ref: ' || COALESCE(CAST(:v_parsed:response:lab_markers:reference_values[m.index] AS STRING), 'N/A')) AS ai_raw
        FROM LATERAL FLATTEN(input => :v_parsed:response:lab_markers:marker_name) m
    );

    -- 4. Log Action
    INSERT INTO VITALIS_DEV.APP.ACTIVITY_LOG (LOG_ID, CUSTOMER_ID, ACTION, DETAILS, USER_NAME)
    SELECT UUID_STRING(), :p_customer_id, 'REPORT_EXTRACTED', 'JSON extracted and flattened', :p_user;

    RETURN 'SUCCESS';
END;
$$;